# Generated by Django 4.2.2 on 2023-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0002_usuario_email_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bars_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
