# Generated by Django 4.2.2 on 2023-07-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0002_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Producto',
            new_name='producto',
        ),
    ]
