# Generated by Django 4.2.2 on 2023-07-14 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
