# Generated by Django 4.2.2 on 2023-07-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_user', '0005_producto_created_at_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
